server {
    listen 80;
    server_name ${CERT_DOMAIN};

    # This HTTP-only config is used only to issue the first certificate.
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
