FROM golang:1.25.5-alpine

WORKDIR /app

RUN apk add --no-cache git build-base
RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

CMD ["air", "-c", ".air.toml"]
